export const categories = [
  "Work",
  "Travel",
  "Home",
  "People",
  "Tech",
  "Food",
  "Misc",
];
export const colors = ["yellow", "blue", "pink", "green"];
export const seed = [
  ["Speakerphone on public transport.", "Priya", "Travel", "yellow", 2341],
  ["Passwords with new rules every time.", "Anonymous", "Tech", "blue", 1987],
  [
    "When an email says “circling back” (it’s been 3 hours).",
    "Matt",
    "Work",
    "pink",
    1654,
  ],
  [
    "People who leave one sip of milk in the carton.",
    "Jess",
    "Home",
    "green",
    1120,
  ],
  ["The algorithm knows me too well.", "A.", "Tech", "pink", 892],
  [
    "When I say “5 more minutes” and it becomes 47.",
    "Liv",
    "Misc",
    "green",
    2118,
  ],
  [
    "Tiny portions for a not-so-tiny price.",
    "Anonymous",
    "Food",
    "yellow",
    1376,
  ],
  ["People who reply “Noted.”", "Dan", "People", "blue", 909],
  ["Easy-peel packaging. We need to talk.", "Sam", "Home", "yellow", 912],
  ["This meeting could have been a nap.", "Jo", "Work", "pink", 231],
  [
    "The wet sleeve after washing your hands.",
    "Anonymous",
    "Misc",
    "blue",
    687,
  ],
  [
    "People who stop at the top of an escalator.",
    "Alex",
    "Travel",
    "green",
    428,
  ],
  ["A recipe’s life story before the recipe.", "Charlie", "Food", "pink", 564],
  ["“Let’s find a time.” The time is never.", "Jules", "People", "yellow", 319],
  ["The printer can smell a deadline.", "Morgan", "Work", "green", 756],
  ["Updating the app made it worse.", "Anonymous", "Tech", "blue", 1034],
].map(([text, signature, category, color, votes], i) => ({
  id: `founding-${i + 1}`,
  text,
  signature,
  category,
  color,
  votes,
  demo: true,
}));
